version: 0.0
os: linux
files:
   - source: /
     destination: /home/ec2-user/pruebas/prueba2
     
permissions:
   - object: /home/ec2-user/pruebas
     pattern: "**"
     mode: 777   
     type: 
       - file
   - object: /home/ec2-user/pruebas
     pattern: "**"
     mode: 777   
     type: 
       - directory  
hooks:
   AfterInstall:
   - location: scripts/ejecutable.sh
